let bikes = [
    {
        id: "1",
        name: "yamaha",
        image: "/assets/bikes/r15.jpg",
        images:["/assets/bikes/r15.jpg","/assets/bikes/r151.jpg","/assets/bikes/r152.jpg","/assets/bikes/r153.jpg"],
        cc: "155",
        mileage: "55",
        price: "10000",
        model: "r15 v3",
        km: "3000",
        year: "2019",
        ownership: "1",
        color: "blue",
        bikeno:"TN 91 J 0450",
        address:"K4.Station,AnnaNagar,Chennai,TamilNadu",
        isSold:false
      
    },
    {

        id: "2",
        name: "royal enfield",
        image: "/assets/bikes/bullet.jpg",
        images:["/assets/bikes/bullet.jpg","/assets/bikes/bullet1.jpg","/assets/bikes/bullet2.jpg","/assets/bikes/bullet3.jpg"],
        cc: "350",
        mileage: "45",
        price: "20000",
        model: "classic 350",
        km: "4000",
        year: "2015",
        ownership: "1",
        color: "black",
        bikeno:"TN 18 AC 1881",
        address:"A1.Station,AnnaNagar,Chennai,TamilNadu,",
        isSold:false
      
       
    },
    {
        id: "3",
        name: "Yamaha",
        image: "/assets/bikes/fz.jpg",
        images:["/assets/bikes/fz.jpg","/assets/bikes/fz1.jpg","/assets/bikes/fz2.jpg","/assets/bikes/fz3.jpg"],
        cc: "153",
        mileage: "60",
        price: "30000",
        model: "fz v1",
        km: "40000",
        year: "2019",
        ownership: "1",
        color: "black",
        bikeno:"TN 03 F 7564",
        address:"A2.Station,Ambattur,Chennai,TamilNadu",
        isSold:false
      
       
    },

    {
        id: "4",
        name: "honda",
        image: "/assets/bikes/dio.jpg",
        images:["/assets/bikes/dio.jpg","/assets/bikes/dio1.jpg","/assets/bikes/dio2.jpg","/assets/bikes/dio5.jpg"],
        cc: "100",
        mileage: "40",
        price: "40000",
        model: "dio",
        km: "2000",
        year: "2017",
        ownership: "1",
        color: "yellow",
        bikeno:"TN 03 X 1689",
        address:"A3.Station,Kolathur,Chennai,TamilNadu",
        isSold:false
      

    },
    {
        id: "5",
        name: "tvs",
        image: "/assets/bikes/ntroq.jpg",
        images:[ "/assets/bikes/ntroq.jpg","/assets/bikes/ntroq1.jpg","/assets/bikes/ntroq2.jpg","/assets/bikes/ntroq3.jpg"],
        cc: "125",
        mileage: "50",
        price: "50000",
        model: "ntroq",
        km: "5000",
        year: "2020",
        ownership: "1",
        color: "red",
        bikeno:"TN 11 AL 4579",
        address:"B1.Station,Vadavalli,Covai,TamilNadu",
   
    },
    {
        id: "6",
        name: "ktm",
        image: "/assets/bikes/duke.jpg",
        images:["/assets/bikes/duke.jpg","/assets/bikes/duke1.jpg","/assets/bikes/duke2.jpg","/assets/bikes/duke3.jpg"],
        cc: "200",
        mileage: "55",
        price: "60000",
        model: "duke",
        km: "6000",
        year: "2016",
        ownership: "1",
        color: "orange&white",
        bikeno:"TN 38 P 1631",
        address:"B4.Station,R.S.Puram,Covai,TamilNadu",
    
    },
    {
        id: "7",
        name: "honda",
        image: "/assets/bikes/activa.jpg",
        images:["/assets/bikes/activa.jpg","/assets/bikes/activa1.jpg","/assets/bikes/activa2.jpg","/assets/bikes/activa3.jpg"],
        cc: "125",
        mileage: "70000",
        price: "350",
        model: "activa",
        km: "7000",
        year: "2017",
        ownership: "1",
        color: "light blue",
        bikeno:"TN 03 AC 6239",
        address:"B4.Station,Sulur,Covai,TamilNadu",
        
    },
    {
        id: "8",
        name: "hondo",
        image: "/assets/bikes/2activa.jpg",
        images:["/assets/bikes/2activa.jpg","/assets/bikes/2activa2.jpg","/assets/bikes/2activa3.jpg","/assets/bikes/2activa4.jpg"],
        cc: "125",
        mileage: "60",
        price: "800000",
        model: "activa",
        km: "80000",
        year: "2015",
        ownership: "2",
        color: "black",
        bikeno:"TN 18 Y 8685",
        address:"c1.Station,Kovilpalayam,Covai,TamilNadu",
        
    },
    {
        id: "9",
        name: "Yamaha",
        image: "/assets/bikes/rx100.jpg",
        images:["/assets/bikes/rx100.jpg","/assets/bikes/rx1001.jpg","/assets/bikes/rx1002.jpg","/assets/bikes/rx1003.jpg"],
        cc: "100",
        mileage: "45",
        price: "90000",
        model: "rx 100",
        km: "10000",
        year: "1999",
        ownership: "3",
        color: "silver",
        bikeno:"TN 02 B 0797",
        address:"S1.Station,Ganapathy,Covai,TamilNadu",
       
    },
    {
        id: "10",
        name: "piaggio",
        image: "/assets/bikes/vespa.JPG",
        images:["/assets/bikes/vespa.JPG","/assets/bikes/vespa1.JPG","/assets/bikes/vespa2.JPG","/assets/bikes/vespa3.png"],
        cc: "125",
        mileage: "50",
        price: "85000",
        model: "vespa zx",
        km: "1000",
        year: "2021",
        ownership: "1",
        color: "blue",
        bikeno:"TN 03 Y 7107",
        address:"K5.Station,Koyambedu,Chennai,TamilNadu",
       
    }
]

export default bikes